# This is a basic workflow to help you get started with Actions

name: CI test

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      branches:
        required: true
        default: 'dev'
        type: choice
        options:
          - main
          - dev
      fastlane:
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS
    # if: ${{ startsWith(github.event.head_commit.message, 'alpha') }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branches }}
      - name: Run a one-line script
        run: echo ${{ inputs.branches }}
